#!/bin/bash
set -euo pipefail

ROOT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
INFRA_DIR="$ROOT_DIR/infra"
OUTPUT_FILE="$ROOT_DIR/cognito.env"

if ! command -v terraform >/dev/null; then
  echo "Terraform is required to export Cognito configuration." >&2
  exit 1
fi

if ! command -v jq >/dev/null; then
  echo "jq is required to parse Terraform outputs." >&2
  exit 1
fi

if [ ! -d "$INFRA_DIR" ]; then
  echo "Unable to locate infra/ directory (looked in $INFRA_DIR)." >&2
  exit 1
fi

pushd "$INFRA_DIR" >/dev/null

if ! terraform output -json >/dev/null 2>&1; then
  echo "Terraform outputs are unavailable. Run 'terraform apply' first." >&2
  exit 1
fi

OUTPUT_JSON=$(terraform output -json)

COGNITO_REGION=$(echo "$OUTPUT_JSON" | jq -r '.aws_region.value // empty')
USER_POOL_ID=$(echo "$OUTPUT_JSON" | jq -r '.user_pool_id.value // empty')
APP_CLIENT_ID=$(echo "$OUTPUT_JSON" | jq -r '.user_pool_client_id.value // empty')

if [ -z "$COGNITO_REGION" ] && [ -n "$USER_POOL_ID" ] && [[ "$USER_POOL_ID" == *_* ]]; then
  COGNITO_REGION=${USER_POOL_ID%%_*}
fi

if [ -z "$COGNITO_REGION" ] || [ -z "$USER_POOL_ID" ] || [ -z "$APP_CLIENT_ID" ]; then
  echo "Missing required Cognito outputs. Ensure terraform apply succeeded." >&2
  exit 1
fi

cat > "$OUTPUT_FILE" <<EOF
# Generated by scripts/export-cognito-env.sh
COGNITO_REGION=$COGNITO_REGION
COGNITO_USER_POOL_ID=$USER_POOL_ID
COGNITO_APP_CLIENT_ID=$APP_CLIENT_ID
VITE_COGNITO_REGION=$COGNITO_REGION
VITE_COGNITO_USER_POOL_ID=$USER_POOL_ID
VITE_COGNITO_APP_CLIENT_ID=$APP_CLIENT_ID
EOF

popd >/dev/null

echo "Cognito configuration written to $OUTPUT_FILE"
echo "Copy this file to your deployment host as /etc/spheres-of-influence/cognito.env"
